# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractevent',
            name='local_classes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.EventLocalClasses'),
        ),
    ]
