# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='_status',
            field=models.CharField(blank=True, choices=[(None, 'Определяется автоматически'), ('DENIED', 'Отменено'), ('POSTPONED', 'Перенесено')], db_column='status', default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='_status',
            field=models.CharField(blank=True, choices=[(None, 'Определяется автоматически'), ('DENIED', 'Отменено'), ('POSTPONED', 'Перенесено')], db_column='status', default=None, max_length=10, null=True),
        ),
    ]
