# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20170706_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='local_classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.EventLocalClasses'),
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='local_classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.EventLocalClasses'),
        ),
    ]
