# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20170709_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_author', to='entities.UserProfile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeats_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.RepeatsType'),
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_actions_author', to='entities.UserProfile'),
        ),
    ]
