# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20170709_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocalclasses',
            name='dance_directions',
            field=models.ManyToManyField(blank=True, to='entities.DanceDirectionClass'),
        ),
        migrations.AlterField(
            model_name='eventlocalclasses',
            name='dance_styles',
            field=models.ManyToManyField(blank=True, to='entities.DanceStyleClass'),
        ),
    ]
