# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20170613_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServices',
            fields=[
                ('employerspage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.EmployersPage')),
                ('contacts', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.ShopContacts')),
                ('employees', models.ManyToManyField(blank=True, to='entities.EmployeesPage')),
                ('locations', models.ManyToManyField(blank=True, to='entities.ShopLocation')),
            ],
            bases=('entities.employerspage',),
        ),
        migrations.CreateModel(
            name='CustomerServicesType',
            fields=[
                ('abstracttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractType')),
                ('title', models.CharField(choices=[('BARBERSHOP', 'Парикмахерская'), ('ATELIER', 'Ателье')], default='BARBERSHOP', max_length=20)),
            ],
            bases=('entities.abstracttype',),
        ),
        migrations.AddField(
            model_name='customerservices',
            name='types',
            field=models.ManyToManyField(blank=True, to='entities.CustomerServicesType'),
        ),
    ]
