# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20170810_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoActionLocalClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dance_directions', models.ManyToManyField(blank=True, to='entities.DanceDirectionClass')),
                ('dance_styles', models.ManyToManyField(blank=True, to='entities.DanceStyleClass')),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='local_classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.PromoActionLocalClasses'),
        ),
    ]
