# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_auto_20170811_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationLocalClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dance_directions', models.ManyToManyField(to='entities.DanceDirectionClass')),
                ('dance_styles', models.ManyToManyField(to='entities.DanceStyleClass')),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
        migrations.CreateModel(
            name='PersonLocalClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dance_directions', models.ManyToManyField(to='entities.DanceDirectionClass')),
                ('dance_styles', models.ManyToManyField(to='entities.DanceStyleClass')),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
        migrations.CreateModel(
            name='PlaceLocalClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dance_directions', models.ManyToManyField(to='entities.DanceDirectionClass')),
                ('dance_styles', models.ManyToManyField(to='entities.DanceStyleClass')),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
        migrations.CreateModel(
            name='SchoolLocalClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dance_directions', models.ManyToManyField(to='entities.DanceDirectionClass')),
                ('dance_styles', models.ManyToManyField(to='entities.DanceStyleClass')),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
        migrations.CreateModel(
            name='TeacherLocalClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dance_directions', models.ManyToManyField(to='entities.DanceDirectionClass')),
                ('dance_styles', models.ManyToManyField(to='entities.DanceStyleClass')),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='local_classes',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entities.PageLocalClasses'),
        ),
        migrations.AlterField(
            model_name='person',
            name='local_classes',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entities.PageLocalClasses'),
        ),
        migrations.AlterField(
            model_name='place',
            name='local_classes',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entities.PlaceLocalClasses'),
        ),
        migrations.AlterField(
            model_name='school',
            name='local_classes',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entities.SchoolLocalClasses'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='local_classes',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entities.PageLocalClasses'),
        ),
    ]
