# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_auto_20170619_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.ArticleLink'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.AudioLink'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.PhotoLink'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.PlaylistLink'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.VideoLink'),
        ),
    ]
