# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_auto_20170620_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceStyleClass',
            fields=[
                ('abstractlocalclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLocalClass')),
            ],
            bases=('entities.abstractlocalclass',),
        ),
        migrations.RenameModel(
            old_name='DanceDirection',
            new_name='DanceDirectionClass',
        ),
        migrations.RemoveField(
            model_name='dancestyle',
            name='abstractlocalclass_ptr',
        ),
        migrations.RemoveField(
            model_name='dancestyle',
            name='dance_direction',
        ),
        migrations.AlterField(
            model_name='eventlocalclasses',
            name='dance_styles',
            field=models.ManyToManyField(to='entities.DanceStyleClass'),
        ),
        migrations.AlterField(
            model_name='pagelocalclasses',
            name='dance_styles',
            field=models.ManyToManyField(to='entities.DanceStyleClass'),
        ),
        migrations.DeleteModel(
            name='DanceStyle',
        ),
    ]
