# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_auto_20170813_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='local_classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.PageLocalClasses'),
        ),
        migrations.AlterField(
            model_name='person',
            name='local_classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.PageLocalClasses'),
        ),
        migrations.AlterField(
            model_name='place',
            name='local_classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.PlaceLocalClasses'),
        ),
        migrations.AlterField(
            model_name='school',
            name='local_classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.SchoolLocalClasses'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='local_classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.PageLocalClasses'),
        ),
    ]
