# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_auto_20170813_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='local_classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.OrganizationLocalClasses'),
        ),
        migrations.AlterField(
            model_name='person',
            name='local_classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.PersonLocalClasses'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='local_classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.TeacherLocalClasses'),
        ),
    ]
