# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_auto_20170620_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancestyleclass',
            name='dance_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.DanceDirectionClass'),
        ),
    ]
