# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_auto_20170817_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServicesContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.UserProfile')),
                ('phone_numbers', models.ManyToManyField(blank=True, to='entities.PhoneNumber')),
                ('socials', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Socials')),
            ],
            options={
                'ordering': ('updated',),
                'abstract': False,
            },
        ),
    ]
