# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_dancestyleclass_dance_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceDirection',
            fields=[
                ('abstractpostgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractPostGroup')),
                ('tags', models.ManyToManyField(blank=True, to='entities.DanceDirectionTag')),
            ],
            bases=('entities.abstractpostgroup',),
        ),
        migrations.CreateModel(
            name='DanceStyle',
            fields=[
                ('abstractpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractPost')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('author_of_post', models.CharField(blank=True, max_length=100)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entities.DanceDirection')),
            ],
            bases=('entities.abstractpost',),
        ),
        migrations.CreateModel(
            name='DanceStyleAuthorLink',
            fields=[
                ('abstractlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLink')),
            ],
            bases=('entities.abstractlink',),
        ),
        migrations.AddField(
            model_name='dancestyle',
            name='link_to_author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.DanceStyleAuthorLink'),
        ),
        migrations.AddField(
            model_name='dancestyle',
            name='tags',
            field=models.ManyToManyField(blank=True, to='entities.DanceStyleTag'),
        ),
    ]
