# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_customerservicescontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='employees',
            field=models.ManyToManyField(blank=True, to='entities.EmployeesPage'),
        ),
    ]
