# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_auto_20170824_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServicesLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.UserProfile')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.City')),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerServicesMapCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.UserProfile')),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='customerservices',
            name='contacts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.CustomerServicesContacts'),
        ),
        migrations.AlterField(
            model_name='customerservices',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.CustomerServicesLocation'),
        ),
        migrations.AddField(
            model_name='customerserviceslocation',
            name='coordinates',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.CustomerServicesMapCoordinates'),
        ),
    ]
