# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_auto_20170825_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancedirection',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='dancestyle',
            name='directions',
        ),
        migrations.AddField(
            model_name='dancedirection',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entities.Direction'),
        ),
        migrations.AddField(
            model_name='dancestyle',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entities.Direction'),
        ),
    ]
