# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_auto_20170830_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.City')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Direction')),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.UserSettings'),
        ),
    ]
