# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_auto_20170920_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.City'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Direction'),
        ),
    ]
