# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_auto_20170920_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_token',
            field=models.TextField(blank=True, help_text='Facebook token for offline access', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blog_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_open_graph',
            field=models.NullBooleanField(help_text='Determines if this user want to share via open graph'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_profile_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='new_token_required',
            field=models.BooleanField(default=False, help_text='Set to true if the access token is outdated or lacks permissions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='raw_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images\\facebook_profiles/%Y/%m/%d'),
        ),
    ]
